Repository Arquisoft/wichat_es6b, pull requests merged in 2025-04, with the labels that each got.

#86 Testing
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.test.js
  webapp/src/game/game.test.js
Labels: testing

#100 Documentacion runtime view
  docs/src/06_runtime_view.adoc
  package-lock.json
Labels: documentation

#104 Develop
  docker-compose.yml
  gatewayservice/gateway-service.js
  llm_key.env
  llmservice/llm-service.js
  package-lock.json
  package.json
  users/historyservice/Dockerfile
  users/historyservice/history-service.js
  users/historyservice/historyservice.yaml
  users/historyservice/package-lock.json
  users/historyservice/package.json
  users/userservice/package-lock.json
  users/userservice/package.json
  users/userservice/user-service.js
  users/userservice/userservice.yaml
  webapp/Dockerfile
  webapp/package-lock.json
  webapp/package.json
  webapp/react_key.env
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/AddUser.js
  webapp/src/components/FlipCard.css
  webapp/src/components/FlipCard.js
  webapp/src/components/Login.js
  webapp/src/components/Ranking.js
  webapp/src/components/UserProfile.js
  webapp/src/game/HourglassTimer.css
  webapp/src/game/HourglassTimer.js
  webapp/src/game/OutTimeMessage.css
  webapp/src/game/ProgressBar.css
  webapp/src/game/game.js
  webapp/src/game/game.test.js
  webapp/src/game/gameManager.js
  webapp/src/game/hintContext.js
  webapp/src/index.js
Labels: sprint

#105 Documentacion
  docs/images/07-deploymentDiagramv2.png
  docs/images/contextAndScope.png
  docs/images/contextAndScopetecnical.png
  docs/package-lock.json
  docs/package.json
  docs/src/01_introduction_and_goals.adoc
  docs/src/02_architecture_constraints.adoc
  docs/src/03_context_and_scope.adoc
  docs/src/06_runtime_view.adoc
  docs/src/07_deployment_view.adoc
  docs/src/10_quality_requirements.adoc
  docs/src/12_glossary.adoc
  package-lock.json
Labels: documentation

#121 Nav y footer con tests y otros arreglos a tests
  docker-compose.yml
  gatewayservice/gateway-service.js
  package-lock.json
  package.json
  questionservice/Dockerfile
  questionservice/all_questions.js
  questionservice/app.css
  questionservice/app.js
  questionservice/docker-compose.yml
  questionservice/guardarPreguntaBaseDatos.js
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/question-model.js
  questionservice/question-service.js
  questionservice/questionGeneration.js
  questionservice/questions.js
  questionservice/questionservice.test.js
  questionservice/questionservice.yaml
  webapp/package-lock.json
  webapp/package.json
  webapp/public/logo_texto.png
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/AddUser.js
  webapp/src/components/AddUser.test.js
  webapp/src/components/FlipCard.css
  webapp/src/components/Footer.js
  webapp/src/components/Footer.test.js
  webapp/src/components/Login.js
  webapp/src/components/Login.test.js
  webapp/src/components/NavBar.js
  webapp/src/components/NavBar.test.js
  webapp/src/game/game.js
  webapp/src/game/game.test.js
  webapp/src/game/gameManager.js
  webapp/src/game/hintContext.js
  webapp/src/index.js
  webapp/src/sessionContext.js
Labels: Requisito de alto nivel

#129 Arreglo juego y niveles dificultad y tematica
  README.md
  docs/images/07-deploymentDiagramv2.png
  docs/images/contextAndScope.png
  docs/images/contextAndScopetecnical.png
  docs/package-lock.json
  docs/package.json
  docs/src/01_introduction_and_goals.adoc
  docs/src/02_architecture_constraints.adoc
  docs/src/03_context_and_scope.adoc
  docs/src/06_runtime_view.adoc
  docs/src/07_deployment_view.adoc
  docs/src/10_quality_requirements.adoc
  docs/src/12_glossary.adoc
  gatewayservice/package-lock.json
  gatewayservice/package.json
  package-lock.json
  questionservice/all_questions.js
  webapp/package-lock.json
  webapp/public/NeonSans.ttf
  webapp/src/App.css
  webapp/src/App.js
  webapp/src/components/GameSettings.js
  webapp/src/components/NavBar.js
  webapp/src/components/Ranking.js
  webapp/src/components/difficulty-selector.css
  webapp/src/game/game.js
  webapp/src/game/gameManager.js
Labels: optional

#151 Arreglo error de seguridad en el servicio de usuarios
  users/userservice/user-service.js
Labels: bug

#158 Test adduser
  webapp/src/components/AddUser.test.js
Labels: testing
